###   token    admin
POST http://localhost:8050/oauth/token?grant_type=password&username=admin&password=admin
Authorization: Basic c3lzdGVtOnN5c3RlbQ==

###   token    aa
POST http://localhost:8050/oauth/token?grant_type=password&username=aa&password=admin
Authorization: Basic c3lzdGVtOnN5c3RlbQ==

###   refresh
POST http://localhost:8050/oauth/token?refresh_token=cc529bf5-7cda-4117-a1b7-af6e1ac625ee
Authorization: Basic c3lzdGVtOnN5c3RlbQ==

###   测试
GET http://localhost:8051/test3?access_token=741d2424-0809-4c08-988b-8196c6361500
Authorization: Basic c3lzdGVtOnN5c3RlbQ==

###



